import AskBar from "@/components/AskBar";
import DevelopmentIntelligenceView from "@/components/intelligence/DevelopmentIntelligenceView";
import type {
  CatalystWithSource,
  Market,
  OpportunityWithSource,
  OpportunityZoneWithSource,
  ProjectWithSource,
} from "@/lib/types";

export const dynamic = "force-static";

// Not linked anywhere in the app nav, and outside middleware.ts's
// /dashboard/:path* auth gate on purpose -- this route exists only to
// render the real dashboard UI (map, legend, AskBar) against entirely
// fictional data, so a marketing screenshot can show the product working
// without exposing any real investor's business data. Nothing here reads
// from Supabase.

const demoMarket: Market = {
  id: "demo-market",
  slug: "demo",
  name: "Topeka",
  state: "KS",
  center_lat: 39.0523,
  center_lng: -95.6802,
  default_zoom: 13,
};

const now = new Date().toISOString();
const today = now.slice(0, 10);

const demoProjects: ProjectWithSource[] = [
  {
    id: "demo-project-1",
    market_id: demoMarket.id,
    parcel_id: null,
    title: "Example Multifamily Development",
    category: "active_development",
    subcategory: "multifamily",
    status: "planning_review",
    plan_category: "development",
    project_type: "multifamily",
    stage: "review_planning",
    description: "Illustrative example -- not a real project.",
    address: "123 Example St",
    latitude: 39.0601,
    longitude: -95.6689,
    project_value: 18500000,
    units: 140,
    acreage: 4.2,
    developer: "Example Development Group",
    contractor: null,
    investor: "Sample Capital Partners",
    date_announced: today,
    date_updated: today,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
  {
    id: "demo-project-2",
    market_id: demoMarket.id,
    parcel_id: null,
    title: "Sample Retail Plaza",
    category: "active_development",
    subcategory: "retail",
    status: "under_construction",
    plan_category: "development",
    project_type: "retail",
    stage: "construction",
    description: "Illustrative example -- not a real project.",
    address: "456 Sample Ave",
    latitude: 39.0455,
    longitude: -95.6912,
    project_value: 6200000,
    units: null,
    acreage: 2.1,
    developer: "Sample Properties LLC",
    contractor: "Sample Construction Co.",
    investor: null,
    date_announced: today,
    date_updated: today,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
  {
    id: "demo-project-3",
    market_id: demoMarket.id,
    parcel_id: null,
    title: "Placeholder Office Park",
    category: "active_development",
    subcategory: "office",
    status: "permitted",
    plan_category: "development",
    project_type: "commercial",
    stage: "permitting",
    description: "Illustrative example -- not a real project.",
    address: "789 Placeholder Rd",
    latitude: 39.038,
    longitude: -95.6558,
    project_value: 9800000,
    units: null,
    acreage: 3.4,
    developer: "Placeholder Holdings",
    contractor: "Placeholder Builders",
    investor: null,
    date_announced: today,
    date_updated: today,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
  {
    id: "demo-project-4",
    market_id: demoMarket.id,
    parcel_id: null,
    title: "Demo Industrial Facility",
    category: "active_development",
    subcategory: "industrial",
    status: "completed",
    plan_category: "development",
    project_type: "industrial",
    stage: "complete",
    description: "Illustrative example -- not a real project.",
    address: "321 Demo Blvd",
    latitude: 39.0685,
    longitude: -95.6435,
    project_value: 24000000,
    units: null,
    acreage: 8.6,
    developer: "Demo Industrial Partners",
    contractor: "Demo Builders Inc.",
    investor: null,
    date_announced: today,
    date_updated: today,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
  {
    id: "demo-project-5",
    market_id: demoMarket.id,
    parcel_id: null,
    title: "Sample Mixed-Use Block",
    category: "planning_entitlement",
    subcategory: "mixed-use",
    status: "proposed",
    plan_category: "land_use",
    project_type: "mixed_use",
    stage: "proposed",
    description: "Illustrative example -- not a real project.",
    address: "555 Fictional Ln",
    latitude: 39.0512,
    longitude: -95.7015,
    project_value: 12300000,
    units: 60,
    acreage: 2.8,
    developer: "Fictional Land Co.",
    contractor: null,
    investor: null,
    date_announced: today,
    date_updated: today,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
];

const demoOpportunities: OpportunityWithSource[] = [
  {
    id: "demo-opp-1",
    market_id: demoMarket.id,
    lead_id: null,
    address: "88 Illustrative Ct",
    latitude: 39.058,
    longitude: -95.6825,
    signals: ["vacant"],
    listing_status: null,
    owner_name: null,
    is_absentee: null,
    years_owned: null,
    estimated_equity: null,
    assessed_value: 145000,
    distress_indicators: null,
    opportunity_score: 78,
    why_flagged: "Illustrative example -- not a real property.",
    date_identified: today,
    asking_price: null,
    estimated_resale_value: null,
    original_list_price: null,
    lot_size_acres: 0.4,
    code_violation_count: null,
    code_violation_summary: null,
    vacant_since: null,
    zoning_district: null,
    permitted_uses: null,
    rezoning_potential: null,
    buildability_notes: null,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
  {
    id: "demo-opp-2",
    market_id: demoMarket.id,
    lead_id: null,
    address: "204 Sample Terrace",
    latitude: 39.0447,
    longitude: -95.6641,
    signals: ["tax_delinquent", "absentee_owner"],
    listing_status: null,
    owner_name: "Sample Owner LLC",
    is_absentee: true,
    years_owned: 11,
    estimated_equity: 92000,
    assessed_value: 168000,
    distress_indicators: ["tax_delinquent"],
    opportunity_score: 87,
    why_flagged: "Illustrative example -- not a real property.",
    date_identified: today,
    asking_price: null,
    estimated_resale_value: null,
    original_list_price: null,
    lot_size_acres: null,
    code_violation_count: null,
    code_violation_summary: null,
    vacant_since: null,
    zoning_district: null,
    permitted_uses: null,
    rezoning_potential: null,
    buildability_notes: null,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
  {
    id: "demo-opp-3",
    market_id: demoMarket.id,
    lead_id: null,
    address: "17 Example Park Dr",
    latitude: 39.0655,
    longitude: -95.6907,
    signals: ["listing"],
    listing_status: "Active",
    owner_name: null,
    is_absentee: null,
    years_owned: null,
    estimated_equity: null,
    assessed_value: null,
    distress_indicators: null,
    opportunity_score: 71,
    why_flagged: "Illustrative example -- not a real property.",
    date_identified: today,
    asking_price: 210000,
    estimated_resale_value: 265000,
    original_list_price: null,
    lot_size_acres: null,
    code_violation_count: null,
    code_violation_summary: null,
    vacant_since: null,
    zoning_district: null,
    permitted_uses: null,
    rezoning_potential: null,
    buildability_notes: null,
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
];

const demoCatalysts: CatalystWithSource[] = [
  {
    id: "demo-catalyst-1",
    market_id: demoMarket.id,
    title: "Example Employer Expansion",
    catalyst_type: "major_employer",
    description: "Illustrative example -- not a real catalyst.",
    address: "1000 Fictional Pkwy",
    latitude: 39.0523,
    longitude: -95.6802,
    influence_radius_meters: 1100,
    boundary: null,
    status: "planning_entitlement",
    estimated_value: 40000000,
    estimated_scale_note: null,
    expected_timeline: null,
    why_it_matters: null,
    development_impact: null,
    related_context: [],
    is_spotlight: false,
    date_announced: today,
    source_id: "demo-source",
    additional_source_ids: [],
    related_shift_id: null,
    related_entitlement_case_id: null,
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    catalyst_score: null,
    reason_for_catalyst_classification: null,
    signal_categories: [],
    signal_confidence: null,
    power_load_mw: null,
    potential_score: null,
    potential_score_components: null,
    opportunity_area: null,
    power_notes: null,
    fiber_notes: null,
    land_notes: null,
    incentives_notes: null,
    development_environment_notes: null,
    risk_notes: null,
    unknowns_to_verify: [],
    why_still_potential: null,
    power_pillar_label: null,
    site_pillar_label: null,
    approval_pillar_label: null,
    entitlement_velocity: null,
    entitlement_velocity_notes: null,
    city_receptiveness: null,
    city_receptiveness_notes: null,
    community_friction: null,
    community_friction_notes: null,
    utility_timeline: null,
    utility_timeline_notes: null,
    water_notes: null,
    natural_gas_notes: null,
    potential_site_type: null,
    people: null,
    readiness_stage: null,
    readiness_notes: null,
    next_steps: [],
    why_this_site: null,
    housing_type: null,
    demand_notes: null,
    entitlement_status: null,
    entitlement_notes: null,
    sewer_notes: null,
    road_notes: null,
    site_notes: null,
    estimated_yield: null,
    economics_notes: null,
    opportunity_catalyst: null,
    infrastructure_type: null,
    infrastructure_subtype: null,
    development_impact_types: [],
    development_impact_level: null,
    impact_area_notes: null,
    related_catalyst_ids: [],
    opportunities_created_notes: null,
    serving_utility: null,
    transmission_voltage_kv: null,
    transmission_distance_miles: null,
    substation_distance_miles: null,
    potential_load_mw_low: null,
    potential_load_mw_high: null,
    available_capacity_status: null,
    interconnection_notes: null,
    total_acreage: null,
    available_acreage_status: null,
    contiguous_acreage: null,
    parcel_count: null,
    floodplain_status: null,
    floodplain_constrained: null,
    zoning_status: null,
    gas_pipeline_distance_miles: null,
    gas_pipeline_operator: null,
    gas_pipeline_diameter_in: null,
    btm_potential_status: null,
    air_permitting_notes: null,
    owners: null,
    primary_advantage: null,
    primary_risk: null,
    developer_assessment: null,
    developer_takeaway: null,
    nearest_substation_name: null,
    ownership_coverage: null,
    source: null,
  },
];

const demoOpportunityZones: OpportunityZoneWithSource[] = [
  {
    id: "demo-zone-1",
    market_id: demoMarket.id,
    title: "Sample Favorable Zoning Area",
    description: "Illustrative example -- not a real zoning determination.",
    zoning_district: "Example Commercial",
    rezoning_notes: null,
    boundary: {
      type: "Polygon",
      coordinates: [
        [
          [-95.6885, 39.062],
          [-95.6845, 39.062],
          [-95.6845, 39.0655],
          [-95.6885, 39.0655],
          [-95.6885, 39.062],
        ],
      ],
    },
    source_id: "demo-source",
    confidence: "verified",
    last_verified_at: now,
    created_at: now,
    source: null,
  },
];

const demoAskAnswer = {
  question: "Where is early development happening?",
  segments: [
    { text: "Right now, " },
    { text: "Example Multifamily Development", type: "project" as const, id: "demo-project-1" },
    { text: " is in the early planning stage on the west side, and " },
    { text: "Sample Retail Plaza", type: "project" as const, id: "demo-project-2" },
    { text: " just broke ground nearby. Both are worth watching over the next few months." },
  ],
};

export default function MarketingPreviewPage() {
  return (
    <div className="min-h-screen bg-[#f4f2ee] p-8">
      <div className="mx-auto max-w-6xl space-y-3">
        <h1 className="text-2xl font-semibold text-[#1c1c1c]">{demoMarket.name}, {demoMarket.state}</h1>
        <AskBar marketName={demoMarket.name} marketSlug={demoMarket.slug} demo={demoAskAnswer} />
        <DevelopmentIntelligenceView
          market={demoMarket}
          projects={demoProjects}
          parcels={[]}
          opportunities={demoOpportunities}
          catalysts={demoCatalysts}
          opportunityZones={demoOpportunityZones}
          growthAreas={[]}
          potentialSites={[]}
          initialCategory="all"
        />
      </div>
    </div>
  );
}
